name: Ejecutar Scraper UCO

on:
  schedule:
    - cron: "0 */2 * * *"  # Ejecutar todos los días a las 12:00 UTC (13:00 en España peninsular)
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Para poder hacer push al repo

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar el scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python scrapper.py

      - name: Subir processed_ids.json al repositorio
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add results/processed_ids.json
          git commit -m "Actualizar processed_ids.json con nuevas publicaciones" || echo "No hay cambios"
          git push
